# Generated by Django 5.1.4 on 2025-05-31 14:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0006_delete_obradearte'),
        ('sales', '0004_remove_orderitem_artwork_orderitem_artwork_name_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='encargo',
            options={'ordering': ['-fecha']},
        ),
        migrations.RemoveField(
            model_name='encargo',
            name='descripcion',
        ),
        migrations.AddField(
            model_name='encargo',
            name='fecha_actualizacion',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='encargo',
            name='artista',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='encargos_artista', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='encargo',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='encargos_cliente', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='encargo',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('confirmado', 'Confirmado'), ('completado', 'Completado'), ('cancelado', 'Cancelado')], default='pendiente', max_length=20),
        ),
        migrations.AlterField(
            model_name='encargo',
            name='obra',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='encargos', to='gallery.comision'),
        ),
        migrations.AlterField(
            model_name='encargo',
            name='plan',
            field=models.CharField(choices=[('basico', 'Básico'), ('estandar', 'Estándar'), ('premium', 'Premium')], default='basico', max_length=20),
        ),
    ]
