# Generated by Django 5.1.4 on 2025-05-31 14:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0006_delete_obradearte'),
        ('sales', '0005_alter_encargo_options_remove_encargo_descripcion_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='encargo',
            options={},
        ),
        migrations.RemoveField(
            model_name='encargo',
            name='fecha_actualizacion',
        ),
        migrations.AlterField(
            model_name='encargo',
            name='artista',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='encargos_recibidos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='encargo',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='encargos_realizados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='encargo',
            name='estado',
            field=models.CharField(default='Pendiente', max_length=20),
        ),
        migrations.AlterField(
            model_name='encargo',
            name='obra',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gallery.comision'),
        ),
        migrations.AlterField(
            model_name='encargo',
            name='plan',
            field=models.CharField(max_length=20),
        ),
    ]
