# Generated by Django 5.1.7 on 2025-04-21 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_add_profile_picture'),
        ('users', '0003_usuario_rol'),
    ]

    operations = [
    ]
