# Generated by Django 5.1.7 on 2025-05-13 19:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_merge_0002_add_profile_picture_0003_usuario_rol'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='seguidores',
            field=models.ManyToManyField(blank=True, related_name='siguiendo', to=settings.AUTH_USER_MODEL),
        ),
    ]
