# Generated by Django 5.1.7 on 2025-05-16 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
        ('users', '0005_usuario_seguidores'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='biografia',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='categorias',
            field=models.ManyToManyField(blank=True, related_name='usuarios', to='categories.categoria'),
        ),
    ]
