# Generated by Django 5.1.7 on 2025-05-16 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_usuario_biografia_usuario_categorias'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='estado',
            field=models.CharField(choices=[('conectado', 'Conectado'), ('ausente', 'Ausente'), ('desconectado', 'Desconectado')], default='desconectado', max_length=20),
        ),
        migrations.AddField(
            model_name='usuario',
            name='ultima_conexion',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
