# Generated by Django 5.1.7 on 2025-05-15 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0003_comentario'),
    ]

    operations = [
        migrations.AddField(
            model_name='obradearte',
            name='imagenes_adicionales',
            field=models.ImageField(blank=True, null=True, upload_to='artworks/additional/'),
        ),
    ]
