# Generated by Django 5.1.7 on 2025-05-15 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0005_remove_obradearte_vendedor_comision_and_more'),
        ('sales', '0003_alter_orderitem_artwork'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ObraDeArte',
        ),
    ]
