# Generated by Django 5.1.4 on 2025-05-31 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0006_delete_obradearte'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comision',
            options={'ordering': ['-fecha_creacion'], 'verbose_name': 'Comisión', 'verbose_name_plural': 'Comisiones'},
        ),
        migrations.AddField(
            model_name='comision',
            name='estado',
            field=models.CharField(choices=[('disponible', 'Disponible'), ('no_disponible', 'No Disponible'), ('en_proceso', 'En Proceso'), ('completada', 'Completada')], default='disponible', max_length=20),
        ),
        migrations.AddField(
            model_name='comision',
            name='fecha_actualizacion',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='comision',
            name='titulo',
            field=models.CharField(max_length=200),
        ),
    ]
