# Generated by Django 5.1.4 on 2025-05-31 12:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mensajes', '0001_initial'),
        ('sales', '0004_remove_orderitem_artwork_orderitem_artwork_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mensaje',
            name='encargo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mensajes', to='sales.encargo'),
        ),
    ]
